issue-144 (Chore): Updated join chat link and year in Footer
open-horizon/open-horizon.github.io pull request #148
Opened 2022-02-12 18:15 UTC by Abhijay007

Signed-off-by: Abhijay Jain <Abhijay007j@gmail.com>

# Pull Request Template

## Description

Updated join chat link and year in the footer.

Fixes #144 

## Type of change

code

Please delete options that are not relevant.

- [x] Bug fix (non-breaking change which fixes an issue)

## How Has This Been Tested?

Tested locally by running server 

## Additional Context (Please include any Screenshots/gifs if relevant)

![image](https://user-images.githubusercontent.com/64387054/153723115-668c8ac0-7d33-4985-a088-3c4ff911a4bf.png)

## Checklist:

- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [x] I have checked my code and corrected any misspellings
- [x] I have tagged the reviewers in a comment below in case my pull request is ready for a review
- [x] I have signed the commit message to agree to the Developer Certificate of Origin (DCO) (to certify that you wrote or otherwise have the right to submit your contribution to the project.) by adding "--signoff" to my git commit command.

2022-02-12 18:15 UTC, Abhijay007 commented
@unnati914 , @joewxboy Please review my PR

2022-02-12 20:43 UTC, joewxboy requested changes
Small issue with using JavaScript like that in the footer:
* If JavaScript is turned off (or not used by machine readers) the copyright statement is not valid.
* If the person viewing it has their date set incorrectly, the copyright year will be wrong.

Unfortunately, we have to hard-code the year and update manually each year. :(

Was the original year 2020?  If so, we need to update the year to show the range 2020-2022

Thanks.

2022-02-13 05:36 UTC, unnati914 approved these changes
lgtm :)

2022-02-14 16:47 UTC, joewxboy approved these changes

2022-02-14 16:47 UTC, merged