Issue-140 (Chore): Updated Open Graph image metadata
open-horizon/open-horizon.github.io pull request #199
Opened 2022-03-06 23:51 UTC by Abhijay007

Signed-off-by: Abhijay Jain <Abhijay007j@gmail.com>

## Description

Updated Open Graph image metadata in the website and optimized for Twitter, Facebook, LinkedIn, etc

Fixes #140 

## Type of change

code

Please delete options that are not relevant.

- [x] Bug fix (non-breaking change which fixes an issue)

## How Has This Been Tested?

Note for reviewers: Not tested as I need to deploy the site for that, it is better to merge this PR after the implementation of "deployment preview GHA" as it generates preview links for the current changes using that link we can check this on various open-graph debugger for platforms like Twitter, Facebook, LinkedIn. 

## Checklist:

- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas
- [x] I have checked my code and corrected any misspellings
- [x] I have tagged the reviewers in a comment below incase my pull request is ready for a review
- [x] I have signed the commit message to agree to Developer Certificate of Origin (DCO) (to certify that you wrote or otherwise have the right to submit your contribution to the project.) by adding "--signoff" to my git commit command.

2022-03-08 03:50 UTC, johnwalicki approved these changes
og: tags are a good idea.  Approved.

The actual png image can be squashed (which we can do in another PR).
I often use a linux cli tool called pngquant to compress images without losing resolution.
This technique speeds up page loads by reducing the image sizes.  In my offline test, the hero-dark-site.png was compressed by 36%

The simplest way to do this would be to add the imgbot app to this repo.  I can do that separately.

2022-03-08 13:37 UTC, joewxboy requested changes
og:type, title, url, image appear to be repeated.  This is not necessary.  Please remove one set of them.

in HTML5, meta tags should be considered container tags, and thus self-closing, but mostly only for backwards-compatibility with XHTML.  This means they should end with `/>` instead of just `>`.

2022-03-08 17:14 UTC, Abhijay007 commented
> og:type, title, url, image appear to be repeated. This is not necessary. Please remove one set of them.
> 
> in HTML5, meta tags should be considered container tags, and thus self-closing, but mostly only for backwards-compatibility with XHTML. This means they should end with `/>` instead of just `>`.

got it, I am removing the repeated type, title, URL, image for Facebook, but for Twitter, I think we need that as Twitter has its own og property

2022-03-09 21:25 UTC, joewxboy approved these changes

2022-03-09 21:25 UTC, merged