Updating docs
open-horizon/open-horizon.github.io pull request #251
Opened 2022-05-06 19:11 UTC by sonaljain067

Signed-off-by: Sonal Jain <sonaljain067@gmail.com>

# Pull Request Template

## Description
This issue fixes Raspbian in documentation to Raspberry Pi OS

Fixes #222 

## Type of change

Please delete options that are not relevant.
[✓] This change requires a documentation update

## How Has This Been Tested?
NA

Please describe the tests that you ran to verify your changes. Provide instructions so we can reproduce. Please also list any relevant details for your test configuration

## Additional Context (Please include any Screenshots/gifs if relevant)

...

## Checklist:

- [✓] My code follows the style guidelines of this project
- [✓ ] I have made corresponding changes to the documentation
- [✓ ] I have tagged the reviewers in a comment below incase my pull request is ready for a review
- [✓ ] I have signed the commit message to agree to Developer Certificate of Origin (DCO) (to certify that you wrote or otherwise have the right to submit your contribution to the project.) by adding "--signoff" to my git commit command.

@johnwalicki Please review my Pull Request

2022-05-06 20:53 UTC, joewxboy requested changes
See inline comments

2022-05-06 20:55 UTC, joewxboy commented on docs/getting_started/known_issues.md
> +* When you are upgrading from Raspberry Pi OS 9 (stretch) to Raspberry Pi OS 10 (buster), a previously installed, configured, and running agent might require reinstallation. In some instances, the ag
It should be:

When you are upgrading from Raspberry Pi OS 10 (buster) or Raspberry Pi OS 11 (bullseye), ...

There is no Raspberry Pi OS 9 (stretch)

2022-05-06 20:55 UTC, joewxboy requested changes

2022-05-06 20:55 UTC, joewxboy commented on docs/installing/adding_devices.md
> +   * {{site.data.keyword.linux_notm}} on ARM (32-bit), for example Raspberry Pi, running Raspberry Pi OS buster or stretch
Instead of "buster or stretch" make it "buster or bullseye"

2022-05-06 21:23 UTC, johnwalicki approved these changes
Fantastic - Thanks

2022-05-07 07:14 UTC, sonaljain067 commented
Done with the changes!

2022-05-07 18:19 UTC, Abhijay007 approved these changes
LGTM

2022-05-07 20:13 UTC, johnwalicki approved these changes
Thanks for the clarifications.

2022-05-07 21:04 UTC, joewxboy approved these changes

2022-05-07 21:05 UTC, joewxboy approved these changes

2022-05-07 21:05 UTC, merged