Issue 410 - broken numeration and code blocks
open-horizon/open-horizon.github.io pull request #411
Opened 2023-02-09 14:01 UTC by oemel09

# Pull Request Template

## Description

Please include a summary of the change and which issue is fixed. Please also include relevant motivation and context. List any dependencies that are required for this change.

Fixes #410 
- Indentation for correct numeration and code blocks
- Add language to code blocks and replace non breaking space with regular spaces for consistency
- copyright updates

## Type of change

Please delete options that are not relevant.
- [x] This change requires a documentation update

## How Has This Been Tested?
View these pages at:
- https://open-horizon.github.io/docs/developing/transform_image/
- https://open-horizon.github.io/docs/developing/model_management_details/

## Checklist:
- [x] I have tagged the reviewers in a comment below incase my pull request is ready for a review
- [x] I have signed the commit message to agree to Developer Certificate of Origin (DCO) (to certify that you wrote or otherwise have the right to submit your contribution to the project.) by adding "--signoff" to my git commit command.

2023-02-09 14:09 UTC, oemel09 commented
@joewxboy @johnwalicki

2023-02-09 14:13 UTC, joewxboy requested changes
Found two items that should be fixed.

2023-02-09 14:13 UTC, joewxboy commented on docs/developing/model_management_details.md
> +   In this example, camera edge nodes node1, node2, and node3 are registered with policy. **weaponDetector** is one of the services running on the nodes, and youwant your model file to be used by the
This change appears to be a mistake.  Words are now runtogether in three places.

2023-02-09 14:13 UTC, joewxboy commented on docs/developing/transform_image.md
> +   The following **publish** command uses the **horizon/service.definition.json** file and your key pair to sign and publish your service to {{site.data.keyword.  horizon_exchange}}. It also pushes y
Space inserted inside a variable substitution name.  Please remove it.

2023-02-09 17:27 UTC, Abhijay007 approved these changes
LGTM 👍

2023-02-14 16:06 UTC, joewxboy approved these changes

2023-02-14 16:06 UTC, merged