Issue 441: synced and updated componet tables
open-horizon/open-horizon.github.io pull request #444
Opened 2023-02-23 14:59 UTC by Demopans

# Pull Request Template

## Description

Please include a summary of the change and which issue is fixed. Please also include relevant motivation and context. List any dependencies that are required for this change.

Fixes # 441

## Type of change

Please delete options that are not relevant.

- [X] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update

## How Has This Been Tested?

Please describe the tests that you ran to verify your changes. Provide instructions so we can reproduce. Please also list any relevant details for your test configuration

## Additional Context (Please include any Screenshots/gifs if relevant)

...

## Checklist:

- [ ] My code follows the style guidelines of this project
- [ ] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [ ] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] New and existing unit tests pass locally with my changes
- [ ] Any dependent changes have been merged and published in downstream modules
- [ ] I have checked my code and corrected any misspellings
- [ ] I have tagged the reviewers in a comment below incase my pull request is ready for a review
- [ ] I have signed the commit message to agree to Developer Certificate of Origin (DCO) (to certify that you wrote or otherwise have the right to submit your contribution to the project.) by adding "--signoff" to my git commit command.

2023-02-23 16:39 UTC, johnwalicki commented
Thanks - this is going in the correct direction!  Merging the tables is an important step.

The next step would be to remove the table completely from the overview_oh.md and only keep the table in the components.md file.

@Demopans - can you push another commit into this PR, and remove the table from overview_oh.md ?

2023-02-23 16:47 UTC, johnwalicki commented
Can you also add a table caption (required to comply with Accessibility guidelines) in the components.md file?
Here is an example:
```
{: caption="Table 1. {{site.data.keyword.ieam}} components" caption-side="top"}
```

2023-02-23 18:56 UTC, Demopans commented
Sure. I'll see to it

2023-02-23 22:23 UTC, johnwalicki requested changes
@Demopans  See below suggestions.  Thanks for the edits!

2023-02-23 22:23 UTC, johnwalicki commented on docs/getting_started/components.md
> +{: caption="Table 1. {{site.data.keyword.ieam}} components" caption-side="top"}
My bad for not being specific.  The table caption should be directly after the table. No extra blank lines.
```
| last entry | 1.0.0 | description |
{: caption="Table 1. {{site.data.keyword.ieam}} components" caption-side="top"}
```

Can you force push another commit into this PR and move the caption line? Thx

2023-02-23 22:23 UTC, johnwalicki commented on docs/getting_started/overview_oh.md
> +{{site.data.keyword.edge_notm}} ({{site.data.keyword.ieam}}) includes [several components](../getting_started/components.md) that are bundled with the product. Please see (Getting Started/Components.
Let's not call Open Horizon a "product".  It's an open source project.
Here is a proposed rewrite of this sentence:
```
For more information about components that are bundled with {{site.data.keyword.ieam}}, see [Components](components.md).
```
Note that both the overview_oh.md and the components.md are in the same ../getting_started/ directory so we don't actually need to use a relative path.

2023-02-25 03:20 UTC, johnwalicki approved these changes

2023-02-25 03:23 UTC, merged

2023-02-25 03:23 UTC, johnwalicki commented
Thanks !!